# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
- name: environment_name
  type: string
- name: build_type
  type: string
- name: environment_file
  type: string
- name: enable_monitoring
  type: string
  default: false

steps:
  - task: UsePythonVersion@0
    displayName: 'Setting Python version'
    inputs:
      versionSpec: '3.6'
  - task: Bash@3
    displayName: 'Install Requirements'
    inputs:
      filePath: Templates/src/install_requirements.sh
  - task: AzureCLI@2
    displayName: Register environment
    inputs:
      azureSubscription: $(ado_service_connection_aml_ws)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        python Templates/src/register_environnment.py \
          -n ${{ parameters.environment_name }} \
          -t ${{ parameters.build_type }} \
          -f ${{ parameters.environment_file }} \
          -m ${{ parameters.enable_monitoring }}