# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:

  # Global
  ap_vm_image: ubuntu-20.04
  location: East US 2
  environment: dev
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps 
  ado_service_connection_rg: Kagool-AIML-COE-ServiceConnection-Dev
  ado_service_connection_aml_ws: Kagool-AIML-COE-ServiceConnection-Dev

  # IaC
  resource_group: rg-kdevops-dev
  aml_workspace: amlmlopspockgl02
  application_insights: aimlopspockgl02
  key_vault: kvmlopspockgl02
  container_registry: crmlopspockgl02
  storage_account: samlopspockgl02

  # ap_vm_image: ubuntu-20.04
  # ado_service_connection_aml_ws: KGL-testusecaes-dev-sc
  # aml_workspace: amlmlopspockgl02
  # environment_conda_yaml: dev
  # environment_name: dev
  # resource_group: rg-kdevops-dev

  # Terraform
#   terraform_version: 0.14.7
#   terraform_workingdir: infrastructure/terraform
#   terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf-state
#   terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tfstate
#   terraform_st_container_name: default
#   terraform_st_key: mlops-tab